package com.maelcolium.telepesa.notification.model;

public enum NotificationType {
    TRANSACTION_SUCCESS,
    TRANSACTION_FAILED,
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    LOAN_APPROVED,
    LOAN_REJECTED,
    PAYMENT_DUE,
    PAYMENT_OVERDUE,
    SECURITY_ALERT,
    WELCOME_MESSAGE,
    PASSWORD_RESET,
    EMAIL_VERIFICATION,
    SMS_VERIFICATION,
    GENERAL_ANNOUNCEMENT,
    PROMOTIONAL_OFFER,
    SYSTEM_MAINTENANCE,
    FRAUD_ALERT,
    SUSPICIOUS_ACTIVITY,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED
} 